---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Instalando HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip && unzip packer.zip
      - echo "Instalando jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Instalando plugins necesarios para Hashicorp Packer"
      - ./packer plugins install github.com/hashicorp/amazon
      - echo "Validando amazon-linux_packer-template.json"
      - ./packer validate amazon-linux_packer-template.json
  build:
    commands:
      - echo "Configurando las credenciales de AWS"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - ACCESS_KEY=$(jq -r '.AccessKeyId' aws_credentials.json)
      - aws configure set aws_access_key_id $ACCESS_KEY
      - SECRET_ACCESS_KEY=$(jq -r '.SecretAccessKey' aws_credentials.json)
      - aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
      - SESSION_TOKEN=$(jq -r '.Token' aws_credentials.json)
      - aws configure set aws_session_token $SESSION_TOKEN
      - echo "Construyendo HashiCorp Packer template, amazon-linux_packer-template.json"
      - ./packer build amazon-linux_packer-template.json
  post_build:
    commands:
      - echo "Se completo la construccion de HashiCorp Packer en `date`"
